Feature: CHUNK-5 exact driver usage

  @real-source
  Scenario: Join the exact session row
    Given a chunk run has a trusted `worker_session_id`
    When metrics joins its profile state
    Then model, provider, API calls, tokens, cache use, and cost status come from the exact session row.

  Scenario: Preserve missing session attribution
    Given a run lacks `worker_session_id`
    When metrics runs
    Then it is counted as unjudged rather than assigned zero usage.

  Scenario: Keep base metrics when profile state is unavailable
    Given a profile state database is unavailable
    When metrics runs
    Then base metrics remain readable and the driver-usage limitation is explicit.

  @real-source
  Scenario: Preserve Hermes cost status
    Given Hermes reports estimated cost with no actual cost
    When metrics renders output
    Then the estimate is labelled estimated and actual cost remains absent.

  Scenario: Render operator and driver cells
    Given `--markdown-row`
    When metrics renders the retro row
    Then operator touches and driver-usage coverage have dedicated cells generated by the script.
